### ISSUE TITLE
Feature request: support value labels

### ISSUE THREAD

**Issue by joshjohanning** [tool3/chartscii#139]
Love this package!

I was trying to recreate some of [`termgraph`](https://github.com/mkaz/termgraph) (python) functionality in JavaScript and this was awesome for that.

I was hoping to see in a future update the ability to label the values?

Something like this - note how this chart has the numerical value to the right of the bar:

```
2007: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 183.32
2008: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 231.23
2009: ▇ 16.43
2010: ▇▇▇▇ 50.21
2011: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 508.97
2012: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 212.05
2014: ▏ 1.00
```

Thanks!

**Comment by tool3** [comment]
@joshjohanning we love you back! 

This is a good one! It’s actually a feature i’ve been meaning to add but completely forgot about it so thanks!

**Comment by joshjohanning** [comment]
@tool3 Thank you! 🙇 



![Image](https://github.com/tool3/chartscii/assets/19912012/33c9556a-be31-4d4e-aa38-b4467707d977)

**Comment by tool3** [comment]
> @tool3 Thank you! 🙇
> 
> ![Image](https://private-user-images.githubusercontent.com/19912012/336466976-33c9556a-be31-4d4e-aa38-b4467707d977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MTExNjQsIm5iZiI6MTcxNzUxMDg2NCwicGF0aCI6Ii8xOTkxMjAxMi8zMzY0NjY5NzYtMzNjOTU1NmEtYmUzMS00ZDRlLWFhMzgtYjQ0Njc3MDdkOTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDE0MjEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZDkyOTAzMGViNmFiNzI5ZmNkM2NiNzQ5ZDVhNjk5ZGZlZTE2NjBmOGI5ZTc5MTk4NmJlZjU1MTUwYzFiZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5WOcROf60oPQ5eVgW9TJKNMtl5oeRt6yu_MHlbTUro8)

With great pleasure! Feel free to suggest more ideas :)
